alias: Atom Lite - UV On
description: ""
triggers:
  - type: turned_on
    device_id: 394aaf8aed2d19daa73c470e17b58f18
    entity_id: 53f3e82af804d050b9293bcd5817c7a5
    domain: light
    trigger: device
conditions: []
actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.atom_lite_atom_rgb_light
    data:
      rgb_color:
        - 218
        - 8
        - 221
      brightness_pct: 50
  - device_id: 5e01a064cec06b1b8f4d827e687eac38
    domain: text
    entity_id: cbce925f849b8cb16a2d385f74c39a51
    type: set_value
    value: UV On
  
  # Set Screen Color to Purple (RGB: 128, 0, 128)
  - service: light.turn_on
    target:
      entity_id: light.atom_s3_screen_color
    data:
      rgb_color: [128, 0, 128]
      brightness: 255 # Full saturation

  - device_id: 5e01a064cec06b1b8f4d827e687eac38
    domain: select
    entity_id: bfcd05bccd61d5f4e3f971c240ae703f
    type: select_option
    option: Light On
  
  # Set Screen Backlight to 75%
  - service: light.turn_on
    target:
      entity_id: light.atom_s3_screen_backlight
    data:
      brightness_pct: 75
mode: single